cc_library(
  name = "branch_cmp",
  hdrs = ["branch_cmp.h"],
  srcs = ["branch_cmp.cc"],
  visibility = ["//visibility:public"],
  deps = [
    "//lib/logic:wires",
    "@com_google_absl//absl/status:statusor",
    "@status_macros//:status_macros",
    "@com_github_google_glog//:glog",
  ],
)