cc_library(
  name = "dram",
  hdrs = ["dram.h"],
  srcs = ["dram.cc"],
  visibility = ["//visibility:public"],
  deps = [
    "//lib/logic:wires",
    "@com_google_absl//absl/status:statusor",
    "@com_google_absl//absl/status:status",
    "@status_macros//:status_macros",
  ],
)
