cc_library(
  name = "alu",
  hdrs = ["alu.h"],
  srcs = ["alu.cc"],
  visibility = ["//visibility:public"],
  deps = [
    "//lib/logic:wires",
    "@com_google_absl//absl/status:statusor",
    "@status_macros//:status_macros",
    "@com_github_google_glog//:glog",
  ],
)