cc_library(
  name = "bus",
  hdrs = ["bus.h"],
  srcs = ["bus.cc"],
  visibility = ["//visibility:public"],
  deps = [
    "//lib/logic:wires",
    "@com_google_absl//absl/status:statusor",
    "@com_google_absl//absl/status:status",
    "//lib/memory:dram",
    "@status_macros//:status_macros",
    "@com_github_google_glog//:glog",
  ],
)
