cc_library(
  name = "imm_decoder",
  hdrs = ["imm_decoder.h"],
  srcs = ["imm_decoder.cc"],
  visibility = ["//visibility:public"],
  deps = [
    "//lib/logic:wires",
    "@com_google_absl//absl/status:statusor",
    "@status_macros//:status_macros",
    "@com_github_google_glog//:glog",
  ],
)